snipaste:
  modelpath: C:\Users\formero\Desktop\projects\SnipasteOCR\models
  path: C:/Users/formero/Pictures/snipaste
  preview_enabled: true
translation:
  from_lang: auto
  secret_id: ÄãµÄsecret_id
  secret_key: ÄãµÄkey
  to_lang: zh
